# Machine Learning:
    
Discover machine learning, where computers use algorithms to access data and learn to solve problems by themselves.

In [1]:
from sklearn import datasets


In [2]:
iris = datasets.load_iris()
digits = datasets.load_digits()
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [3]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit([[0,0],[1,1],[2,2]],[0,1,2])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [6]:
reg.coef_

array([0.5, 0.5])

# KNN(K-Nearest Neighbour)

In [7]:
x = [[0],[1],[2],[3]]
y = [0,0,1,1]
from sklearn.neighbors import KNeighborsClassifier

In [8]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [10]:
print(neigh.predict([[1.1]]))

[0]


In [11]:
print(neigh.predict_proba([[1.1]]))

[[0.66666667 0.33333333]]


# Decision Tree

In [13]:
from sklearn import tree
x = [[0,0],[1,1]]
y =[0,1]
clf = tree.DecisionTreeClassifier()
clf.fit(x,y)
clf.predict([[2.,2.]])


array([1])

In [14]:
clf.predict_proba([[2.,2.]])

array([[0., 1.]])

In [15]:
from sklearn.datasets import load_iris
from sklearn import tree

In [16]:
iris = load_iris()
clf = tree.DecisionTreeClassifier()

In [17]:
clf = clf.fit(iris.data, iris.target)

In [18]:
print(clf)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


In [20]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap


In [44]:
import graphviz
dot_data = tree.export_graphviz(clf,out_file=None)
graph = graphviz.Source(dot_data)
graph.render("iris")

# It will generate the decision tree for datasets

ModuleNotFoundError: No module named 'graphviz'

In [51]:
# precision =  tp / (tp + fp)  The ratio of correct answers
# Recall = tp / (tp + fn)   The ratio of true examples that are correctly identified

# F1 Score:   F1 = 2 (P * R / P + R )
# If F = 1 best Score
# If F = 0 worst Score

from sklearn.metrics import precision_recall_fscore_support
y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])
precision_recall_fscore_support(y_true, y_pred, average='macro')


(0.2222222222222222, 0.3333333333333333, 0.26666666666666666, None)

In [23]:
precision_recall_fscore_support(y_true, y_pred, average='micro')


(0.3333333333333333, 0.3333333333333333, 0.3333333333333333, None)

In [24]:
precision_recall_fscore_support(y_true, y_pred, average='weighted')


(0.2222222222222222, 0.3333333333333333, 0.26666666666666666, None)

In [25]:
precision_recall_fscore_support(y_true, y_pred, average=None,
labels=['pig', 'dog', 'cat'])


(array([0.        , 0.        , 0.66666667]),
 array([0., 0., 1.]),
 array([0. , 0. , 0.8]),
 array([2, 2, 2], dtype=int64))

# Supervised Learning Models

In [28]:
# SVM

In [29]:
from sklearn import svm

In [30]:
x = [[0,0],[1,1]]
y = [0,1]
svM = svm.SVC()

In [31]:
svM.fit(x,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
svM.predict([[2.,2.]])

array([1])

In [33]:
svM.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [34]:
svM.support_

array([0, 1])

In [35]:
svM.n_support_

array([1, 1])

In [36]:
# Naive Bayes 

In [37]:
from sklearn.naive_bayes import MultinomialNB


In [38]:
import numpy as np
x =  np.random.randint(5,size=(6,100))
print(x)

[[3 4 2 1 1 4 4 1 4 2 4 2 0 3 1 3 1 2 0 0 3 0 0 1 0 2 0 1 1 2 3 4 2 2 3 2
  4 3 4 0 3 1 1 0 2 3 3 0 0 2 0 3 1 1 1 1 2 4 3 3 1 3 1 0 1 1 3 1 2 3 0 4
  2 3 3 0 3 2 4 3 3 0 4 2 3 0 3 4 3 0 3 2 0 1 1 1 1 4 1 0]
 [2 2 4 1 0 2 4 2 1 3 1 4 2 2 4 2 4 2 0 4 0 3 2 0 0 3 0 1 0 2 0 2 2 1 0 0
  2 2 2 4 4 4 3 2 4 1 1 0 3 0 1 4 3 0 1 0 0 2 1 4 3 4 0 4 0 2 3 3 1 2 0 0
  0 2 1 3 3 2 1 3 3 4 0 3 1 0 0 1 1 1 1 1 0 2 0 1 3 4 2 2]
 [4 0 3 3 3 0 0 2 4 2 1 3 1 3 3 4 4 2 0 0 3 0 4 2 2 3 3 3 2 4 3 2 1 3 4 3
  1 1 4 3 0 0 4 3 2 2 2 4 1 3 0 4 4 4 3 3 3 1 1 4 1 2 2 0 4 3 2 3 2 4 4 2
  1 2 4 4 4 0 0 3 0 0 4 2 2 4 1 4 2 2 0 0 0 3 1 0 3 2 3 0]
 [4 4 4 1 1 1 4 3 0 0 1 1 4 3 3 2 4 2 2 4 0 3 4 0 3 2 0 3 3 1 2 0 0 0 1 0
  1 0 4 0 0 3 3 1 2 0 0 1 2 4 1 4 3 0 1 3 3 0 0 4 1 0 1 0 0 0 2 1 3 0 2 0
  1 1 4 0 2 0 0 2 2 3 4 3 4 4 0 4 2 0 2 0 3 0 0 0 1 0 4 3]
 [4 0 3 1 1 2 2 4 1 0 1 0 3 0 3 1 4 2 3 1 1 0 3 2 0 4 4 2 1 1 1 0 1 1 2 2
  4 3 4 1 1 2 4 1 4 1 3 4 2 4 2 3 1 3 3 0 3 1 2 2 4 4 1 2 1 3 1 3 3 2 3 2
  4 3 4 4 4 2 1 4 2 0 4 

In [39]:
y = np.array([1,2,3,4,5,6])

In [40]:
nb = MultinomialNB()
nb.fit(x,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [41]:
print(nb.predict(x[2:3]))

[3]


# Unsupervised Learning

In [46]:
# PCA

In [47]:
import numpy as np
from sklearn.decomposition import PCA


In [48]:
x = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])

In [49]:
pca = PCA(n_components=2)
pca.fit(x)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [50]:
print(pca.explained_variance_ratio_)

[0.99244289 0.00755711]


In [1]:
import numpy as np
import numpy.linalg as la
A = np.matrix([[1,2],[3,4]])
print(round(la.det(A)))

-2.0
